CREATE TABLE "public"."custom_broadcast_messages" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topic" text,
  "topic_naming_instructions" text,
  "events" jsonb,
  "topic_description" text,
  "where_topic_is_referenced" jsonb
);

ALTER TABLE "public"."custom_broadcast_messages" ENABLE ROW LEVEL SECURITY;

-- Only Supabase Admins can access this table since it doesn't have any business meaning.
CREATE POLICY "Authenticated users can view"
ON "public"."custom_broadcast_messages"
FOR SELECT
TO authenticated
USING ( true );
