CREATE TABLE "public"."orders_members" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" varchar(24) NOT NULL,
  "member_id" varchar(24) NOT NULL,

  CONSTRAINT fk_order_id
    FOREIGN KEY("order_id")
    REFERENCES "public"."orders"(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_member_id
    FOREIGN KEY("member_id")
    REFERENCES "public"."members"(id),

-- Prevent duplicate order and member rows
  CONSTRAINT unique_order_id_member_id
    UNIQUE(order_id, member_id)
 );
